# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AKingDsq   #标题
subtitle: 'AKingDsq的个人博客'    #副标题
description: '开源精神！！！'    #个性签名
keywords: zh-CN
author: AKingDsq   #作者
language: zh-CN    #语言
timezone: Asia/Shanghai    #中国的时区

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://akingdsq.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/AkingDsq/AkingDsq.github.io.git
  branch: main
  token: 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

# hexo-admin authentification
admin:
  username: AKingDsq
  password_hash: 
  secret: 18079463112

plugins:
  - hexo-asset-img
  - hexo-toc
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-permalink-pinyin
  - hexo-wordcount
  - hexo-generator-searchdb

# 加速hexo-offline-popup
offline_popup:
enable: true

# hexo-toc 插件
toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: '#'
    style: header-anchor

# hexo-asset-image本地预览图片修复插件
marked:								
  prependRoot: true
  postAsset: true

# hexo-prism-plugin代码高亮
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'     #主题选项
  line_number: true    # default false
  custom_css:

# hexo-permalink-pinyin中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

# hexo-wordcount文章字数统计插件
postInfo:
  date: true
  update: true
  wordCount: true # 设置文章字数统计为 true.
  totalCount: true # 设置站点文章总字数统计为 true.
  min2read: true # 阅读时长.
  readCount: true # 阅读次数.

# hexo-generator-searchdb搜索
search:
  path: search.xml
  field: post
  content: true
  format: html
  